# Generated by Django 2.2 on 2019-05-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qID', models.CharField(max_length=50)),
                ('qText', models.CharField(max_length=50)),
                ('qPrompt1', models.CharField(max_length=50)),
                ('qPrompt2', models.CharField(max_length=50)),
                ('qPrompt3', models.CharField(max_length=50)),
                ('qAnswer', models.CharField(max_length=50)),
                ('qFailNext1', models.CharField(max_length=50)),
                ('qFailNext2', models.CharField(max_length=50)),
                ('qFailNext3', models.CharField(max_length=50)),
                ('qSuccessNext', models.CharField(max_length=50)),
            ],
        ),
    ]
