# Generated by Django 2.2 on 2019-06-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qSms',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='qSmsFail1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='qSmsFail2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='qSmsFail3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='qSol',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
