# Generated by Django 2.2 on 2019-06-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190605_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='answersBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studenID', models.CharField(max_length=50)),
                ('qID', models.CharField(max_length=50)),
                ('questionScore', models.PositiveIntegerField()),
            ],
        ),
    ]
